language: node_js
sudo: false
node_js:
  - '8'
  - '10'
services:
  - docker
## Prevent from verbose install log caused by cypress installation
env:
  - CI=true
## Cache NPM folder and cypress binary
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
